import Present from "@/types/Present";

export const LIST_MODELS: {
  model: string;
  presents: Present[];
}[] = [
  { model: "Vazia", presents: [] },
  {
    model: "Casamento",
    presents: [
      {
        id: "1",
        listId: "",
        title: "Obrigar o noivo a tirar foto",
        description: "Ele vai sorrir... nem que seja com dor.",
        price: 200,
        uid: "",
      },
      {
        id: "2",
        listId: "",
        title: "Maracujina para os noivos",
        description:
          "Porque nem só de amor se vive, às vezes precisa de calmante.",
        price: 150,
        uid: "",
      },
      {
        id: "3",
        listId: "",
        title: "Cobertor para a noiva que está sempre coberta de razão",
        description: "Conforto e verdade em uma só peça.",
        price: 225,
        uid: "",
      },
      {
        id: "4",
        listId: "",
        title: "Um gato para os noivos não cuidarem só da vida dos outros",
        description: "Agora eles terão outras sete vidas pra cuidar.",
        price: 250,
        uid: "",
      },
      {
        id: "5",
        listId: "",
        title: "Rolo de macarrão para quando o noivo aprontar",
        description: "Apenas disfarçado de utensílio doméstico.",
        price: 150,
        uid: "",
      },
      {
        id: "6",
        listId: "",
        title: "Capacete para o noivo se proteger do rolo de macarrão",
        description: "Prevenção é tudo no casamento.",
        price: 150,
        uid: "",
      },
      {
        id: "7",
        listId: "",
        title: "Despedida de solteiro do noivo",
        description: "A última festa... ou pelo menos é o que ele vai dizer.",
        price: 290,
        uid: "",
      },
      {
        id: "8",
        listId: "",
        title: "Procedimentos estéticos pro casal continuar lindo",
        description: "Porque o amor é cego, mas a selfie não.",
        price: 200,
        uid: "",
      },
      {
        id: "9",
        listId: "",
        title: "Ajude a pagar o cartão de crédito",
        description: "Mais romântico que flores: boletos pagos.",
        price: 300,
        uid: "",
      },
      {
        id: "10",
        listId: "",
        title: "Um ano de barba feita para o noivo",
        description: "Porque a noiva merece um lenhador e não um urso.",
        price: 300,
        uid: "",
      },
      {
        id: "11",
        listId: "",
        title: "Alexa para a noiva não mandar só no noivo",
        description: "Agora ela comanda por voz também!",
        price: 310,
        uid: "",
      },
      {
        id: "12",
        listId: "",
        title: "Vale churrasco (garanta sua vaga no próximo churras)",
        description: "Carnes, risadas e fofocas garantidas.",
        price: 320,
        uid: "",
      },
      {
        id: "13",
        listId: "",
        title: "3 meses de Netflix garantidos!",
        description: "Casal que maratona unido permanece unido.",
        price: 250,
        uid: "",
      },
      {
        id: "14",
        listId: "",
        title: "Aluguel de bebê para treinamento",
        description: "Só por 48h, com devolução garantida.",
        price: 380,
        uid: "",
      },
      {
        id: "15",
        listId: "",
        title: "Taxa para pegar o buquê",
        description: "Investimento para as próximas núpcias.",
        price: 380,
        uid: "",
      },
      {
        id: "16",
        listId: "",
        title: "Dia off da noiva com as amigas",
        description: "Spa, risadas e zero notificações do noivo.",
        price: 400,
        uid: "",
      },
      {
        id: "17",
        listId: "",
        title: "Taxa para não jogar o buquê na sua namorada",
        description: "Evite DRs futuras, pague agora.",
        price: 400,
        uid: "",
      },
      {
        id: "18",
        listId: "",
        title: "Passeio de balão para esquecer a fatura do cartão",
        description: "Subindo os dois: o balão e os juros.",
        price: 450,
        uid: "",
      },
      {
        id: "19",
        listId: "",
        title: "Viagem de volta ao mundo em 1 ano para a sogra",
        description: "Ela ama vocês... mas de longe é melhor.",
        price: 500,
        uid: "",
      },
      {
        id: "20",
        listId: "",
        title: "Seja nosso parente preferido",
        description: "Cargo vitalício com direito a privilégios exclusivos.",
        price: 800,
        uid: "",
      },
      {
        id: "21",
        listId: "",
        title: "A espera de um milagre",
        description: "Contribua com fé... e um pouquinho de dinheiro.",
        price: 1000,
        uid: "",
      },
      {
        id: "22",
        listId: "",
        title: "Sal grosso para espantar o mal olhado",
        description: "O casamento agradece, e os invejosos também.",
        price: 200,
        uid: "",
      },
      {
        id: "23",
        listId: "",
        title: "Contribuição livre para os indecisos",
        description:
          "Não achou um presente com sua cara? Manda qualquer valor aqui que tá tudo certo!",
        price: 0,
        uid: "",
      },
    ],
  },
];
